version: "3"

services:
  shareyourcloning:
    build: .
    image: manulera/shareyourcloning
    # For eLabFTW
    # image: manulera/shareyourcloning:latest-syc-base
    ports:
      - "8000:8000"

    environment:
    #
    #   If you want to allow other origins via CORS (comma separated)
    #   IMPORTANT: Do not add a trailing slash to the URLs:
    #     > Do not use http://localhost:3000/, but http://localhost:3000
    #     - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    #
    #   If you want to use a subpath of the domain, set ROOT_PATH,
    #   this is the equivalent of --root-path in uvicorn, so the routes
    #   without this prefix will also work (e.g. / will be the same as /shareyourcloning/).
    #   IMPORTANT: Do not add trailing slash, and don't use quotes.
    # - ROOT_PATH=/shareyourcloning
    #
    #   Set this if you are not using "/" as rooth path. Note the trailing slash.
    # - BACKEND_URL=/shareyourcloning/
    #   Set this if you want to use plannotate
      - PLANNOTATE_URL=http://plannotate:8000

  plannotate:
    image: manulera/plannotate-api
