name: Publish to Docker Hub
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: manulera/opencloning

      - name: Build and push Docker image (release)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            manulera/opencloning:latest
            manulera/opencloning:prod
            manulera/opencloning:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (release-oc)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            manulera/opencloning:prod-oc-base
            manulera/opencloning:${{ github.ref_name }}-oc-base

          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FRONTEND_TAG=prod-oc-base

      - name: Build and push Docker image (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            manulera/opencloning:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (workflow_dispatch-oc)
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            manulera/opencloning:latest-oc-base
          build-args: |
            FRONTEND_TAG=latest-oc-base
