name: Prepare release
on:
  workflow_dispatch:

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest frontend release
        id: get_frontend_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/manulera/ShareYourCloning_frontend/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest backend release
        id: get_backend_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/manulera/ShareYourCloning_backend/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "next"
          release_name: "Draft Release"
          body: |
            This release includes:

            Frontend: [${{ fromJson(steps.get_frontend_release.outputs.data).tag_name }}](https://github.com/manulera/ShareYourCloning_frontend/releases/tag/${{ fromJson(steps.get_frontend_release.outputs.data).tag_name }})
            Backend: [${{ fromJson(steps.get_backend_release.outputs.data).tag_name }}](https://github.com/manulera/ShareYourCloning_backend/releases/tag/${{ fromJson(steps.get_backend_release.outputs.data).tag_name }})
          draft: true
          prerelease: false
